# ── RDS master password ───────────────────────────────────────────────────────
# Generated by Terraform so we can construct DATABASE_URL automatically.
# Marked sensitive — never appears in plan/apply output.
# Stored in Terraform state (ensure S3 backend has encryption enabled).
# Excludes characters that break URL parsing in connection strings

resource "random_password" "rds" {
  length  = 32
  special = false  # No special chars — avoids URL parsing in DATABASE_URL
}

module "rds_kobo" {
  source  = "terraform-aws-modules/rds/aws"
  version = "7.1.0"

  identifier = "${local.name_prefix}-postgres"

  # ── Engine ────────────────────────────────────────────────────────────────
  engine         = "postgres"
  engine_version = "14"
  family         = "postgres14"
  instance_class = "db.t3.micro"

  # ── Storage ───────────────────────────────────────────────────────────────
  allocated_storage     = 20
  max_allocated_storage = 100
  storage_type          = "gp3"
  storage_encrypted     = true

  # ── Credentials ──────────────────────────────────────────────────────────
  db_name  = "kobocat"
  username = "meal"
  port     = "5432"

  # We manage the password ourselves — Terraform generates it and stores
  # the full connection URL in Secrets Manager automatically.
  manage_master_user_password = false
  password_wo                 = random_password.rds.result
  password_wo_version         = 1

  # ── Network ───────────────────────────────────────────────────────────────
  create_db_subnet_group = true
  subnet_ids             = module.vpc.private_subnets
  db_subnet_group_name   = "${local.name_prefix}-postgres"

  vpc_security_group_ids = [module.db_sg.security_group_id]
  publicly_accessible    = false

  # ── SSL enforcement ───────────────────────────────────────────────────────
  # Rejects any connection attempt that does not use TLS.
  parameters = [
    {
      name         = "rds.force_ssl"
      value        = "1"
      apply_method = "pending-reboot"
    }
  ]

  # PostgreSQL does not support option groups
  create_db_option_group = false

  # ── Availability ──────────────────────────────────────────────────────────
  # Single-AZ for minimum cost.
  # Change multi_az = true before go-live if budget allows (~$12/month extra).
  multi_az          = false
  availability_zone = "${var.region}a"

  # ── Backups ───────────────────────────────────────────────────────────────
  backup_retention_period = 7
  backup_window           = "03:00-04:00"
  maintenance_window      = "Mon:04:00-Mon:05:00"

  auto_minor_version_upgrade  = true
  allow_major_version_upgrade = false

  # ── Logs ──────────────────────────────────────────────────────────────────
  enabled_cloudwatch_logs_exports        = ["postgresql"]
  create_cloudwatch_log_group            = true
  cloudwatch_log_group_retention_in_days = 30

  # ── Protection ────────────────────────────────────────────────────────────
  deletion_protection              = var.ENV_PREFIX == "prod" ? true : false
  skip_final_snapshot              = var.ENV_PREFIX == "prod" ? false : true

  //deletion_protection              = var.ENV_PREFIX == "dev" ? true : false
  //skip_final_snapshot              = var.ENV_PREFIX == "dev" ? false : true


  final_snapshot_identifier_prefix = "${local.name_prefix}-final"
  delete_automated_backups         = false

  tags = local.common_tags
}

# ── Outputs ───────────────────────────────────────────────────────────────────
output "rds_endpoint" {
  description = "RDS hostname"
  value       = module.rds_kobo.db_instance_address
}

output "rds_port" {
  description = "RDS port"
  value       = module.rds_kobo.db_instance_port
}