namespace: dev
#frontend
frontend:
  name: frontend
  replicas: 1
  labels:
    app: frontend
    component: frontend
  image:
    repository: 466872246229.dkr.ecr.us-east-1.amazonaws.com/frontend-repository
    tag: "latest"
    pullPolicy: IfNotPresent
  containerPort: 80
  serviceAccountName: default
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  podAnnotations: {}
  env: []
  #service
  service:
    name: frontend
    type: ClusterIP
    port: 80
