namespace: dev

gatewayClass:
  name: eg
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  syncWaves: "0"

gateway:
  name: eg
  namespace: gateway
  syncWaves: "1"


app:
  HTTPRoute:
    name: dev-app-route
    syncWaves: "2"
    hostName: "dev.example.com"
    path: /
    serviceName: frontend
    port: 80  

