#secrete store
secretStore:
  name: cluster-secret-store
  provider:
    service: SecretsManager
    region: us-east-1
  serviceAccount:
    name: external-secrets-sa
    namespace: external-secrets
#service account
serviceAccount:
  name: external-secrets-sa
  namespace: external-secrets
  roleArn: arn:aws:iam::290488660393:role/external-secrets-irsa-20260624170942202800000012
#external secrete
externalSecret:
  secretStore:
    name: cluster-secret-store
  name: db-credentials
  target: db-credentials
  refreshInterval: 5m0s
  remoteRef:
    key: crud-dev/rds/credentials
