namespace: dev
#secrete store
secretStore:
  name: cluster-secret-store
  provider:
    service: SecretsManager
    region: us-east-1
  serviceAccount:
    name: external-secrets-sa
    namespace: external-secrets
#external secrete
externalSecret:
  secretStore:
    name: cluster-secret-store
  name: db-credentials
  target: db-credentials
  refreshInterval: 5m0s
  remoteRef:
    key: eso-dev/rds/credentials

