#backend
backend:
  name: backend
  replicas: 1
  labels:
    app: backend
    component: backend
  image:
    repository: 466872246229.dkr.ecr.us-east-1.amazonaws.com/backend-repository
    tag: "latest"
    pullPolicy: IfNotPresent
  containerPort: 8000
  serviceAccountName: default
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
  podAnnotations: {}
  envFrom:
    secretRef:
      name: db-credentials #must match with external secret store target 
  #service    
  service:
    name: backend
    type: ClusterIP
    port: 8000
#config    
dbConfig:
  name: db-credentials
  dbname: posgressdb
  host: "dev-db.c0nu6occexai.us-east-1.rds.amazonaws.com"
  port: "5432"
#external secrete
externalSecret:
  secretStore:
    name: cluster-secret-store
  name: db-credentials
  target: db-credentials
  refreshInterval: 5m0s
  remoteRef:
    key: arn:aws:secretsmanager:us-east-1:466872246229:secret:rds!db-01cbfbc8-9e69-4556-8968-5684a2ffb86e-8jD5rK