apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.target }}
    creationPolicy: Owner
  data:
  - secretKey: DB_USER
    remoteRef: 
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: {{ .Values.externalSecret.remoteRef.key }}
      property: username
  - secretKey: DB_PASSWORD 
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: {{ .Values.externalSecret.remoteRef.key }}
      property: password
  - secretKey: DB_HOST
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: {{ .Values.externalSecret.remoteRef.key }}
      property: host 
  - secretKey: DB_PORT 
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: {{ .Values.externalSecret.remoteRef.key }}
      property: port
  - secretKey: DB_NAME
    remoteRef:
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
      key: {{ .Values.externalSecret.remoteRef.key }}
      property: dbname          
